### ISSUE TITLE
RFC: CONTRIBUTING.md

### ISSUE THREAD

**Issue by lily-mayfield** [LeadPages/gcloud_requests#3]
I'd like input on the CONTRIBUTING.md (contributor's guide) for this repository.

**Comment by bendemaree** [comment]
Sure!

- Google-style docstrings: fine with me, except this repo doesn't use 'em at all yet, so we'd need to convert to do this.
- I thought a bunch this weekend about keeping up a `develop` branch and I don't think we should here. We can simplify things a lot for this (relatively small) project by tagging `master` and having `HEAD@master` be `develop`, basically. Otherwise I think we'd end up merging to `develop`, and strictly merging that into `master`, which doesn't make `develop` too useful.

Do we want to move testing info into the contributing guide? I think it deserves a link from the main readme, but might be nice to move it in here. Also, it's wrong now, as we can't have Travis run tests on PRs due to having some encrypted files required for the build. :sob: On merge we can, but we will likely have to manually run tests as maintainers for PRs.
